- name: ğŸ” Show host being rebooted
  ansible.builtin.debug:
    msg: "Rebooting {{ inventory_hostname }}"

- name: ğŸ” Reboot the server
  ansible.windows.win_reboot:
    reboot_timeout: "{{ windows_reboot_reboot_timeout }}"
    test_command: 'whoami'

- name: âœ… Reboot complete
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} has been rebooted."
