---
- hosts: all
  gather_facts: no
  connection: httpapi
  tasks:
    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getGlobalSearch
        path_params:
          domainUUID: e276abec-e0f2-11e3-8169-6d9ed49b625f
        query_params:
          filter: 172.86.112.36
